name: AccuKnox Secret Scan Workflow

on:
  push:
    branches:
      - secret
  pull_request:

jobs:
  secret_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: AccuKnox Secret Scan
        uses: accuknox/secret-scan-action@v1.0.1
        with:
          accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
          accuknox_endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}
          accuknox_label: secret-scan
          fail: true
          use_extended_ruleset: false
